syntax = "proto3";

package services.unr;

service UnrService {
    rpc unrBaseCreate(UnrBaseRequest) returns (UnrBaseResponse);
    rpc unrBaseRead(UnrBaseRequest) returns (UnrBaseResponse);
    rpc unrBaseUpdate(UnrBaseRequest) returns (UnrBaseResponse);
    rpc unrBaseDelete(UnrBaseRequest) returns (UnrBaseResponse);

    rpc unrRelationshipCreate(UnrRelationshipRequest) returns (UnrRelationshipResponse);
    rpc unrRelationshipRead(UnrRelationshipRequest) returns (UnrRelationshipResponse);
    rpc unrRelationshipUpdate(UnrRelationshipRequest) returns (UnrRelationshipResponse);
    rpc unrRelationshipDelete(UnrRelationshipRequest) returns (UnrRelationshipResponse);
}

message UnrBaseRequest {
    repeated string id = 1;
}

message UnrRelationshipRequest {
    string id = 1;
    string parent_id = 2;
}

message UnrBaseResponse {
    repeated BaseInfo base_info = 1;
}

message UnrRelationshipResponse {
    RelationshipInfo relationship_info = 1;
}

message BaseInfo {
    string id = 1;
    string address = 2;
    string type = 3;
    string protocol = 4;
}

message RelationshipInfo {
    string parent_id = 1;
    repeated string child_ids = 2;
}

