syntax = "proto3";

package services.unr;

service  {
    rpc unrBaseCreate(UnrRequest) returns (UnrBaseResponse);
    rpc unrBaseRead(UnrRequest) returns (UnrBaseResponse);
    rpc unrBaseUpdate(UnrRequest) returns (UnrBaseResponse);
    rpc unrBaseDelete(UnrRequest) returns (UnrBaseResponse);

    rpc unrRelationshipCreate(UnrRequest) returns (UnrRelationshipResponse);
    rpc unrRelationshipRead(UnrRequest) returns (UnrRelationshipResponse);
    rpc unrRelationshipUpdate(UnrRequest) returns (UnrRelationshipResponse);
    rpc unrRelationshipDelete(UnrRequest) returns (UnrRelationshipResponse);
}

message UnrRequest {
    repeated string device_name = 1;
}

message UnrBaseResponse {
    repeated BaseInfo base_info = 1;
}

message UnrRelatioshipResponse {
    repeated RelationshipInfo relationship_info = 1;
}

message BaseInfo {
    string id = 1;
    string address = 2;
    string type = 3;
    string protocol = 4;
}

message RelationshipInfo {
    string parent_id = 1;
    repeated string child_ids = 2;
}

