syntax = "proto3";

package services.unr;

service  {
    rpc unrBaseCreate(unrRequest) returns (unrBaseResponse);
    rpc unrBaseRead(unrRequest) returns (unrBaseResponse);
    rpc unrBaseUpdate(unrRequest) returns (unrBaseResponse);
    rpc unrBaseDelete(unrRequest) returns (unrBaseResponse);

    rpc unrRelationshipCreate(unrRequest) returns (unrRelationshipResponse);
    rpc unrRelationshipRead(unrRequest) returns (unrRelationshipResponse);
    rpc unrRelationshipUpdate(unrRequest) returns (unrRelationshipResponse);
    rpc unrRelationshipDelete(unrRequest) returns (unrRelationshipResponse);
}

message unrRequest {
    repeated string device_name = 1;
}

message unrBaseResponse {
    repeated BaseInfo = 1;
}

message unrRelatioshipResponse {
    repeated RelationshipInfo = 1;
}

message BaseInfo {
    string id = 1;
    string address = 2;
    string type = 3;
    string protocol = 4;
}

message RelationshipInfo {
    string parentId = 1;
    repeated string childIds = 2;
}

