syntax = "proto3";

package services.alarm_commands;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

import "proto/controls/common/v1/alarm.proto";

service AlarmCommands {
  rpc Acknowledge(AcknowledgeRequest)
      returns (google.protobuf.Empty);
      
  rpc Activate(ActivateRequest)
      returns (google.protobuf.Empty);

  rpc Bypass(BypassRequest)
      returns (google.protobuf.Empty);

  rpc GetSnapshot(google.protobuf.Empty) 
      returns (SnapshotResponse);

  rpc Snooze(SnoozeRequest)
      returns (google.protobuf.Empty);
}

message AcknowledgeRequest {
  repeated string devices = 1;
  string user = 2;
}

message ActivateRequest {
  repeated string devices = 1;
  string user = 2;
}

message BypassRequest {
  repeated string devices = 1;
  string user = 2;
}

message SnapshotResponse {
  repeated common.alarm.Status snapshot = 1;
}

message SnoozeRequest {
  repeated string devices = 1;
  string user = 2;
  google.protobuf.Timestamp wake = 3;
}
