syntax = "proto3";

package services.base_info;

service BaseInfoService {
    rpc create(BaseRequest) returns (BaseResponse);
    rpc read(BaseRequest) returns (BaseResponse);
    rpc update(BaseRequest) returns (BaseResponse);
    rpc delete(BaseRequest) returns (BaseResponse);    
}

message request {
    repeated string id = 1;
}

message BaseResponse {
    repeated BaseInfo base_info = 1;
}

message BaseInfo {
    string id = 1;
    string address = 2;
    string type = 3;
    string protocol = 4;
}
