name: Build and Deploy dpm gRPC Modules to GitHub Packages

on:
  push:
    branches:
      - 'main'
    paths:
      - 'deprecated/**'

permissions:
  contents: read
  packages: write

jobs:
  release:
    name: Release proto-generated modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
           <servers>
             <server>
               <id>github</id>
               <username>${{ github.actor }}</username>
               <password>${{ secrets.GITHUB_TOKEN }}</password>
             </server>
           </servers>
          </settings>
          EOF

      - name: Maven deploy
        run: |
          mvn clean package -DskipTests
          mvn clean deploy -Pclient -DskipTests
          mvn clean deploy -Pserver -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

